currsos/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from currsos.views import AsignacionView, AsignacionNew, AsignacionEdit, AsignacionDel


urlpatterns = [
    path('asignacion/', AsignacionView.as_view(), name='alumn_list'),
    path('asignacion/new', AsignacionNew.as_view(), name='asignacion_new'),
    path('asignacion/edit/<int:pk>', AsignacionEdit.as_view(), name='asignacion_edit'),
    path('asignacion/delete/<int:pk>', AsignacionDel.as_view(), name='asignacion_del'),
]

misitio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('currsos.urls', 'app'), namespace='app')),
    path('app/', include(('currsos.urls', 'app'), namespace='apps')),
    path('admin/', admin.site.urls),

]

currsos/models.py
from django.db import models

# Create your models here.
class Alumnos(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    

    def __str__(self):
        return self.nombre

class Cursos(models.Model):
    nombre = models.CharField(max_length=50)
    alumnos = models.ManyToManyField(Alumnos, through='Asignacion')

    def __str__(self):
        return self.nombre

class Asignacion(models.Model):
    alumnos =  models.ForeignKey(Alumnos, on_delete=models.CASCADE)
    cursos = models.ForeignKey(Cursos, on_delete=models.CASCADE)
    fecha_asignacion = models.DateField()

    def __str__(self):
        return '%s %s'%(self.alumnos, self.cursos)

currsos/forms.py
from django import forms 

from .models import Asignacion, Alumnos, Cursos

class AsignacionForm(forms.ModelForm):
    alum = forms.ModelChoiceField(
        queryset = Alumnos.objects.all()
        .order_by('nombre')
    )
    cur = forms.ModelChoiceField(
        queryset = Cursos.objects.all()
        .order_by('nombre')
    )
    class Meta:
        model = Asignacion
        fields = ['alum', 'cur', 'fecha_asignacion']
        labels = {'fecha_asignacion':"fecha_asignacion"}
        widget = {'fecha_asignacion': forms.TextInput}

    def _init_(self, *args, **kwargs):
        super()._init_(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['alum'].empty_label = "Seleccione Alumno"
        self.fields['cur'].empty_label = "Seleccione Curso"
        

currsos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.http import HttpResponseRedirect
#from django.view.generic import CreateView

from .models import Asignacion
from .forms import AsignacionForm

class AsignacionView(LoginRequiredMixin, generic.ListView):
    model = Asignacion
    template_name = 'app/alumn_list.html'
    context_object_name = 'obj'
    login_url = 'app:login'

class AsignacionNew(LoginRequiredMixin, generic.CreateView):
    model = Asignacion
    template_name = "app/alum_form.html"
    context_object_name = "obj"
    form_class = AsignacionForm
    success_url = reverse_lazy("app:alumn_list")
    login_url = 'app:login'

class AsignacionEdit(LoginRequiredMixin, generic.UpdateView):
    model = Asignacion
    template_name = "app/alum_form.html"
    context_object_name = "obj"
    form_class = AsignacionForm
    success_url = reverse_lazy("app:alumn_list")
    login_url = 'app:login'

class AsignacionDel(LoginRequiredMixin, generic.DeleteView):
    model = Asignacion
    template_name = "app/catalogo_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy("app:alumn_list")

currsos/templates/app/alum_form.html
{% block page_content %}
<form method="POST" class="form-inline">
   {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Asignacion
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col-5">
                                <div class="input-group">
                                    {{ form.alum }}
                                </div>
                            </div>
                            <div class="col-5">
                                <div class="input-group">
                                    {{ form.cur}}
                                </div>
                            </div>
                            <div class="col-5">
                                <div class="input-group">
                                    {{ form.fecha_asignacion }}
                                </div>
                            </div>
                            <!-- {{form.as_p}} -->
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"> <span class="fa fa-save"></span>Guardar</button>
                                <a href="{% url 'app:alumn_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}

currsos/templates/app/alumn_list.html
{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de asignaciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">acciones</div>
                <a class="dropdown-item" href="{% url 'app:asignacion_new' %}" ><i class="far fa-calendar-plus"></i> Nueva</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay Asignaciones </div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>alumnos</th>
                <th>cursos</th>
                <th>fecha_asignacion</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.alumnos }}</td>
                    <td>{{ item.cursos }}</td>
                    <td>{{ item.fecha_asignacion }}</td>
                    <td>
                        <a href="{% url 'app:asignacion_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                        <a href="{% url 'app:asignacion_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    //LLamando al dataTables jQuery plugin
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>
{% endblock%}

currsos/templates/app/catalogo_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"> ¿Eliminar ?</div>
                            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Si, Eliminar</button>
                            <!--<a href="{% url 'educacion:parentesco_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>-->
                            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}